apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: nosqls.database.example.com   # (MUST) == plural.APIGroup
spec:
  group: database.example.com     # APIGroup of the custom API
  names:
    kind: NoSQL
    plural: nosqls
  versions:
    - name: v1alpha1              # version of the custom API
      schema:                     # schema / spec of the custom API
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                location:
                  type: string
                  oneOf:
                    - pattern: '^EU$'
                    - pattern: '^US$'
              required:
                - location
      served: true
      referenceable: true
  claimNames:
    kind: NoSQLClaim
    plural: nosqlclaim